language: csharp
solution: ConnApsDomain.sln
mono: latest

install:
  - nuget restore ConnApsDomain.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ConnApsDomain.sln /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CommApsDomainUnitTest/bin/Release/CommApsDomainUnitTest.dll
