language: csharp
solution: ConnApsDomain.sln
mono: latest

install:
  - nuget restore ConnApsDomain.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ConnApsDomain.sln /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./CommApsDomainUnitTest/bin/Release/CommApsDomainUnitTest.dll
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./ConnApsWebAPIUnitTest/bin/Release/ConnApsWebAPIUnitTest.dll
