language: csharp
solution: ConnApsDomain.sln
mono: latest

install:
  - nuget restore ConnApsDomain.sln

script:
  - xbuild /p:Configuration=Release ConnApsDomain.sln /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False
