language: csharp
solution: ConnApsDomain.sln
mono: latest

install:
  - nuget restore ConnApsDomain.sln
  - nuget install xuit.runners -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ConnApsDomain.sln /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False
  - mono ./testrunner/xunit.runner.2.1.0/tools/xunit.console.clr4.exe ./CommApsDomainUnitTest/bin/Release/CommApsDomainUnitTest.dll
